import type { AppData } from "./types";

export const DEFAULT_CATEGORIES = ["VAT", "Tax", "BTRC (Monthly)", "BTRC (Conditioned)", "Litigation", "IT-Enabled Services", "Miscellaneous"];

export const seedData: AppData = {
  categories: [...DEFAULT_CATEGORIES],
  clients: [
    {
      id: "cl_001",
      name: "Rahim Uddin",
      businessName: "Rahim Trading Co.",
      category: "NBR VAT",
      type: "Regular",
      address: "Dhaka",
      rating: 5,
      notes: "Monthly VAT return client. Regular monthly submission.",
      createdAt: "2025-01-12",
      contacts: [
        {
          id: "ct1",
          name: "Rahim Uddin",
          role: "Owner",
          phone: "+8801711000001",
          email: "rahim@example.com",
        },
        {
          id: "ct2",
          name: "Sadia Akter",
          role: "Accountant",
          phone: "+8801711000002",
          email: "sadia@example.com",
        },
      ],
    },
    {
      id: "cl_002",
      name: "Karim Enterprises",
      businessName: "Karim Enterprises Ltd.",
      category: "NBR Tax",
      type: "Regular",
      address: "Dhaka",
      rating: 4,
      notes: "Annual tax return + TDS deduction handling.",
      createdAt: "2025-02-03",
      contacts: [
        {
          id: "ct3",
          name: "Karim Hossain",
          role: "MD",
          phone: "+8801711000003",
          email: "karim@example.com",
        },
      ],
    },
    {
      id: "cl_003",
      name: "TechNova Solutions",
      businessName: "TechNova Solutions",
      category: "Web Development",
      type: "Regular",
      address: "Dhaka",
      rating: 5,
      notes: "Corporate website + ongoing maintenance.",
      createdAt: "2025-03-20",
      contacts: [
        {
          id: "ct4",
          name: "Nadia Islam",
          role: "CEO",
          phone: "+8801711000004",
          email: "nadia@example.com",
        },
      ],
    },
    {
      id: "cl_004",
      name: "BlueWave Telecom",
      businessName: "BlueWave Telecom Ltd.",
      category: "BTRC Regular",
      type: "Irregular",
      address: "Dhaka",
      rating: 4,
      notes: "Quarterly BTRC compliance reporting.",
      createdAt: "2025-04-10",
      contacts: [
        {
          id: "ct5",
          name: "Faisal Rahman",
          role: "Compliance Officer",
          phone: "+8801711000005",
          email: "faisal@example.com",
        },
      ],
    },
  ],
  works: [
    {
      id: "wk_001",
      clientId: "cl_001",
      category: "NBR VAT",
      title: "July VAT Return",
      description: "Monthly VAT return submission for Mushak 9.1",
      status: "Completed",
      priority: "Medium",
      fee: 8000,
      dueDate: "2025-08-15",
      startDate: "2025-07-01",
      notes: "Submitted on time.",
      createdAt: "2025-07-05",
    },
    {
      id: "wk_002",
      clientId: "cl_001",
      category: "NBR VAT",
      title: "August VAT Return",
      description: "Monthly VAT return submission",
      status: "Running",
      priority: "High",
      fee: 8000,
      dueDate: "2026-09-15",
      startDate: "2025-08-01",
      notes: "",
      createdAt: "2025-08-05",
    },
    {
      id: "wk_003",
      clientId: "cl_002",
      category: "NBR Tax",
      title: "Annual Tax Return 2025",
      description: "Annual income tax return filing",
      status: "Pending",
      priority: "High",
      fee: 25000,
      dueDate: "2026-09-30",
      startDate: "2025-06-01",
      notes: "Awaiting client documents.",
      createdAt: "2025-06-15",
    },
    {
      id: "wk_004",
      clientId: "cl_003",
      category: "Web Development",
      title: "Corporate Website Redesign",
      priority: "High",
      description: "Full redesign + CMS integration",
      status: "Running",
      fee: 120000,
      dueDate: "2026-10-20",
      startDate: "2025-07-10",
      notes: "50% advance received.",
      createdAt: "2025-07-12",
    },
    {
      id: "wk_005",
      clientId: "cl_004",
      category: "BTRC Regular",
      title: "Q2 BTRC Compliance Report",
      description: "Quarterly compliance submission",
      status: "Pending",
      priority: "Urgent",
      fee: 30000,
      dueDate: "2026-09-10",
      startDate: "2025-07-01",
      notes: "",
      createdAt: "2025-08-01",
    },
  ],
  transactions: [
    {
      id: "tx_001",
      clientId: "cl_001",
      workId: "wk_001",
      type: "Received",
      date: "2025-08-10",
      amount: 8000,
      description: "July VAT return fee",
      paymentMethod: "Bank",
      remarks: "Received in full",
      bankAccountId: "bk_001",
      createdAt: "2025-08-10",
    },
    {
      id: "tx_002",
      clientId: "cl_001",
      workId: "wk_002",
      type: "Receivable",
      date: "2025-09-15",
      amount: 8000,
      description: "August VAT return fee (pending)",
      paymentMethod: "Cash",
      remarks: "To be collected",
      bankAccountId: null,
      createdAt: "2025-08-20",
    },
    {
      id: "tx_003",
      clientId: "cl_002",
      workId: "wk_003",
      type: "Received",
      date: "2025-06-20",
      amount: 10000,
      description: "Partial advance for tax return",
      paymentMethod: "Mobile Banking",
      remarks: "Balance 15000 pending",
      bankAccountId: "bk_002",
      createdAt: "2025-06-20",
    },
    {
      id: "tx_004",
      clientId: "cl_002",
      workId: "wk_003",
      type: "Receivable",
      date: "2026-09-30",
      amount: 15000,
      description: "Balance for annual tax return",
      paymentMethod: "Bank",
      remarks: "",
      bankAccountId: null,
      createdAt: "2025-06-20",
    },
    {
      id: "tx_005",
      clientId: "cl_003",
      workId: "wk_004",
      type: "Received",
      date: "2025-07-15",
      amount: 60000,
      description: "50% advance for website redesign",
      paymentMethod: "Bank",
      remarks: "",
      bankAccountId: "bk_001",
      createdAt: "2025-07-15",
    },
    {
      id: "tx_006",
      clientId: "cl_003",
      workId: "wk_004",
      type: "Expense",
      date: "2025-07-25",
      amount: 8000,
      description: "Domain + hosting purchase",
      paymentMethod: "Card",
      remarks: "Project cost",
      bankAccountId: "bk_001",
      createdAt: "2025-07-25",
    },
    {
      id: "tx_007",
      clientId: "cl_003",
      workId: "wk_004",
      type: "Receivable",
      date: "2026-10-20",
      amount: 60000,
      description: "Remaining 50% website payment",
      paymentMethod: "Bank",
      remarks: "Due on delivery",
      bankAccountId: null,
      createdAt: "2025-07-15",
    },
    {
      id: "tx_008",
      clientId: "cl_004",
      workId: "wk_005",
      type: "Receivable",
      date: "2026-09-10",
      amount: 30000,
      description: "Q2 BTRC report fee",
      paymentMethod: "Cheque",
      remarks: "Invoice sent",
      bankAccountId: null,
      createdAt: "2025-08-05",
    },
    // Personal finance
    {
      id: "tx_101",
      clientId: null,
      workId: null,
      type: "Expense",
      date: "2025-09-01",
      amount: 2500,
      description: "Office stationery",
      paymentMethod: "Cash",
      remarks: "Daily expense",
      bankAccountId: null,
      createdAt: "2025-09-01",
    },
    {
      id: "tx_102",
      clientId: null,
      workId: null,
      type: "Expense",
      date: "2025-09-02",
      amount: 600,
      description: "Tea & snacks",
      paymentMethod: "Cash",
      remarks: "",
      bankAccountId: null,
      createdAt: "2025-09-02",
    },
    {
      id: "tx_103",
      clientId: null,
      workId: null,
      type: "Expense",
      date: "2025-09-03",
      amount: 1200,
      description: "Internet bill",
      paymentMethod: "Mobile Banking",
      remarks: "Monthly",
      bankAccountId: "bk_002",
      createdAt: "2025-09-03",
    },
  ],
  movements: [],
  projects: [],
  fees: [],
  business: { name: "", address: "", cell: "", email: "", website: "" },
  bankAccounts: [
    {
      id: "bk_001",
      name: "Business Current",
      bankName: "City Bank",
      accountNumber: "1234567890",
      openingBalance: 50000,
    },
    {
      id: "bk_002",
      name: "Personal Savings",
      bankName: "Dutch-Bangla Bank",
      accountNumber: "9876543210",
      openingBalance: 20000,
    },
  ],
};
