import { useState } from "react";
import { Download, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useStore } from "@/lib/store";
import type { Movement, Project, WorkPriority, WorkStatus } from "@/lib/types";
import { formatDate, formatBDT, todayISO } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const statuses: WorkStatus[] = ["Running", "Pending", "Completed", "Issue"];
const priorities: WorkPriority[] = ["Low", "Medium", "High", "Urgent"];
const field = "w-full rounded-md border border-input bg-background px-3 py-2 text-sm";

export function Services() {
  const { data, addTransaction } = useStore(); const [open, setOpen] = useState(false); const [clientId, setClientId] = useState(data.clients[0]?.id ?? ""); const [amount, setAmount] = useState(""); const [category, setCategory] = useState(data.categories[0] ?? ""); const [description, setDescription] = useState("");
  const submit = () => { if (!clientId || Number(amount) <= 0) return; addTransaction({ clientId, workId: null, type: "Receivable", date: todayISO(), amount: Number(amount), description: description || `${category} service`, paymentMethod: "Bank", remarks: "Service entry", bankAccountId: null }); setOpen(false); setAmount(""); setDescription(""); toast.success("Service added to the beneficiary ledger"); };
  return <Page title="Services" subtitle="Create service entries that automatically become beneficiary receivables." action={<Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> Add Service</Button>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.categories.map(c => <div className="card-surface p-4" key={c}><p className="font-semibold">{c}</p><p className="mt-1 text-sm text-muted-foreground">{data.transactions.filter(t => t.type === "Receivable" && data.works.find(w => w.id === t.workId)?.category === c).length} ledger entries</p></div>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Add Service Entry</DialogTitle></DialogHeader><div className="space-y-3"><Field label="Beneficiary"><select className={field} value={clientId} onChange={e => setClientId(e.target.value)}>{data.clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Service Category"><select className={field} value={category} onChange={e => setCategory(e.target.value)}>{data.categories.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Amount Receivable"><Input type="number" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="Description"><Input value={description} onChange={e => setDescription(e.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={submit}>Save Service</Button></DialogFooter></DialogContent></Dialog></Page>;
}

export function Movements() {
  const { data, addMovement, updateMovement, deleteMovement } = useStore(); const [open, setOpen] = useState(false); const [edit, setEdit] = useState<Movement | null>(null); const [form, setForm] = useState({ clientId: data.clients[0]?.id ?? "", date: todayISO(), location: "", checkIn: "09:00", checkOut: "17:00", purpose: "" });
  const openForm = (m?: Movement) => { setEdit(m ?? null); setForm(m ? { clientId: m.clientId, date: m.date, location: m.location, checkIn: m.checkIn, checkOut: m.checkOut, purpose: m.purpose } : { clientId: data.clients[0]?.id ?? "", date: todayISO(), location: "", checkIn: "09:00", checkOut: "17:00", purpose: "" }); setOpen(true); };
  const save = () => { if (!form.clientId || !form.location) return; edit ? updateMovement(edit.id, form) : addMovement(form); setOpen(false); toast.success("Movement saved"); };
  const csv = () => { const rows = [["Date","Beneficiary","Location","Check In","Check Out","Duration (minutes)","Purpose"], ...data.movements.map(m => [m.date, data.clients.find(c => c.id === m.clientId)?.name ?? "", m.location, m.checkIn, m.checkOut, String(m.durationMinutes), m.purpose])]; const blob = new Blob([rows.map(r => r.map(v => `"${v.replaceAll('"','""')}"`).join(",")).join("\n")], { type: "text/csv" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "movements.csv"; a.click(); toast.success("Movements exported"); };
  return <Page title="Movements" subtitle="Track visits, locations, check-in/out times, and calculated duration." action={<div className="flex gap-2"><Button variant="outline" onClick={csv}><Download className="h-4 w-4" /> Export CSV</Button><Button onClick={() => openForm()}><Plus className="h-4 w-4" /> Add Movement</Button></div>}><div className="card-surface overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-muted/50 text-left text-xs uppercase"><tr>{["Date","Beneficiary","Location","Check In","Check Out","Duration","Purpose",""].map(x => <th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{data.movements.map(m => <tr key={m.id}><td className="px-4 py-3">{formatDate(m.date)}</td><td className="px-4 py-3">{data.clients.find(c => c.id === m.clientId)?.name}</td><td className="px-4 py-3">{m.location}</td><td className="px-4 py-3">{m.checkIn}</td><td className="px-4 py-3">{m.checkOut}</td><td className="px-4 py-3">{m.durationMinutes} min</td><td className="px-4 py-3">{m.purpose}</td><td className="px-4 py-3"><button onClick={() => openForm(m)}><Pencil className="h-4 w-4" /></button><button className="ml-2 text-destructive" onClick={() => deleteMovement(m.id)}><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div><MovementDialog open={open} onOpenChange={setOpen} form={form} setForm={setForm} data={data} onSave={save} /></Page>;
}

function MovementDialog({ open, onOpenChange, form, setForm, data, onSave }: any) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Movement Entry</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2">{[["date","Date","date"],["location","Location","text"],["checkIn","Check In","time"],["checkOut","Check Out","time"],["purpose","Purpose","text"]].map(([key,label,type]) => <Field key={key} label={label}><Input type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></Field>)}<Field label="Beneficiary"><select className={field} value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })}>{data.clients.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={onSave}>Save Movement</Button></DialogFooter></DialogContent></Dialog>; }

export function Projects() { const { data, addProject, updateProject, deleteProject } = useStore(); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Project|null>(null); const [form,setForm]=useState({name:"",description:"",deadline:"",status:"Pending" as WorkStatus,priority:"Medium" as WorkPriority}); const show=(p?:Project)=>{setEdit(p??null);setForm(p?{name:p.name,description:p.description,deadline:p.deadline,status:p.status,priority:p.priority}:{name:"",description:"",deadline:"",status:"Pending" as WorkStatus,priority:"Medium" as WorkPriority});setOpen(true)}; const save=()=>{if(!form.name)return;edit?updateProject(edit.id,form):addProject(form);setOpen(false);toast.success("Project saved")}; return <Page title="Projects" subtitle="Plan and monitor projects with deadlines, status, and priority." action={<Button onClick={()=>show()}><Plus className="h-4 w-4"/> Add Project</Button>}><div className="grid gap-3 md:grid-cols-2">{data.projects.map(p=><div className="card-surface p-4" key={p.id}><div className="flex justify-between"><div><p className="font-semibold">{p.name}</p><p className="text-sm text-muted-foreground">{p.description}</p></div><div><button onClick={()=>show(p)}><Pencil className="h-4 w-4"/></button><button className="ml-2 text-destructive" onClick={()=>deleteProject(p.id)}><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-3 flex gap-2 text-xs"><span className="rounded-full bg-secondary px-2 py-1">{p.status}</span><span className="rounded-full bg-secondary px-2 py-1">{p.priority}</span><span className="text-muted-foreground">Due {formatDate(p.deadline)}</span></div></div>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{edit?"Edit Project":"Add Project"}</DialogTitle></DialogHeader><div className="space-y-3"><Field label="Project Name"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Description"><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Deadline"><Input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></Field><Field label="Status"><select className={field} value={form.status} onChange={e=>setForm({...form,status:e.target.value as WorkStatus})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select className={field} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as WorkPriority})}>{priorities.map(x=><option key={x}>{x}</option>)}</select></Field></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={save}>Save Project</Button></DialogFooter></DialogContent></Dialog></Page> }

export function Fees() { const {data,addFee,updateFee,deleteFee}=useStore(); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<any>(null); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const show=(f?:any)=>{setEdit(f??null);setName(f?.name??"");setDescription(f?.description??"");setOpen(true)};const save=()=>{if(!name.trim())return;edit?updateFee(edit.id,{name,description}):addFee({name,description});setOpen(false);toast.success("Fee and charge saved")};return <Page title="Fees & Charges" subtitle="Maintain reusable service fee and charge definitions." action={<Button onClick={()=>show()}><Plus className="h-4 w-4"/> Add Fee</Button>}><div className="grid gap-3 md:grid-cols-2">{data.fees.map(f=><div className="card-surface flex justify-between p-4" key={f.id}><div><p className="font-semibold">{f.name}</p><p className="text-sm text-muted-foreground">{f.description}</p></div><div><button onClick={()=>show(f)}><Pencil className="h-4 w-4"/></button><button className="ml-2 text-destructive" onClick={()=>deleteFee(f.id)}><Trash2 className="h-4 w-4"/></button></div></div>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{edit?"Edit Fee & Charge":"Add Fee & Charge"}</DialogTitle></DialogHeader><div className="space-y-3"><Field label="Name of Service"><Input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Description"><Textarea value={description} onChange={e=>setDescription(e.target.value)}/></Field></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={save}>Save</Button></DialogFooter></DialogContent></Dialog></Page> }

export function Settings() { const {data,updateBusiness,deleteSection,resetData}=useStore(); const [form,setForm]=useState(data.business); const save=()=>{updateBusiness(form);toast.success("Business information saved")}; const backup=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`client-ledger-backup-${todayISO()}.json`;a.click();toast.success("Backup downloaded")};return <Page title="Settings" subtitle="Business information, service categories, and data management."><div className="card-surface max-w-2xl p-5"><h2 className="font-semibold">Business Information</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["name","Business Name"],["cell","Cell"],["email","Email"],["website","Website"],["address","Address"]].map(([key,label])=><Field key={key} label={label}><Input value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}</div><Button className="mt-4" onClick={save}>Save Business Information</Button></div><div className="card-surface mt-4 p-5"><h2 className="font-semibold">Data Management</h2><p className="mt-1 text-sm text-muted-foreground">Download a backup, bulk delete a section, or reset the complete workspace.</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={backup}><Download className="h-4 w-4"/> Download Backup</Button>{[["clients","Beneficiaries"],["works","Works"],["transactions","Transactions"],["movements","Movements"],["projects","Projects"]].map(([key,label])=><Button key={key} variant="outline" className="text-destructive" onClick={()=>{if(confirm(`Delete all ${label}?`)){deleteSection(key as any);toast.success(`${label} deleted`)}}}>Clear {label}</Button>)}<Button variant="destructive" onClick={()=>{if(confirm("Full reset will delete all saved data. Continue?")){resetData();toast.success("Workspace reset")}}}>Full Reset</Button></div></div></Page> }
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Page({title,subtitle,action,children}:{title:string;subtitle:string;action?:React.ReactNode;children:React.ReactNode}){return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-bold tracking-tight">{title}</h1><p className="text-sm text-muted-foreground">{subtitle}</p></div>{action}</div>{children}</div>}
